done
odin11/hw_1.1 pull request #1
Opened 2022-01-08 21:17 UTC by odin11

2022-01-08 21:23 UTC, odin11 commented on src/ru/skypro/Main.java
> +        float zpD2 = zpD * 1.1f;
тип short,int - ошибка; var - почему то в конечном выводе получалось нецелочисленное значение

2022-01-08 21:25 UTC, odin11 commented on src/ru/skypro/Main.java
> +        int daysAverage = targetInKg * 1000 / ((mode1+mode2) / 2) + 1; /*формулировку "в среднем" трактую
здесь возможны различия в трактовках и результатач

2022-01-09 17:52 UTC, rmuhamedgaliev requested changes
Привет! 
Неплохо сделал, задание, есть некоторые неточности. Посмотри пожалуйста в PR и исправь замечания. 

Успехов в обучении! Не сбавляй оборотов! 💪

2022-01-09 17:52 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        int totalWeight = 5 * wBanana + 200/100 * wMilkPer100Ml + 2 * wPlombir + 4 * wEgg;
стилистика пляшет, где-то есть пробелы между знаками а где-то нету. В IDEA есть автоматический инструмент форматирования https://blog.jetbrains.com/idea/2020/06/code-formatting/

Хорошо написанный код проще читать

2022-01-09 17:52 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        byte wBanana = 80;
лучше писать полные названия сокращать не обязательно, это может помешать пониманию кода

2022-01-09 17:52 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        float w1 = 78.2f;
числа в переменных необходимо избегать

2022-01-09 17:52 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        int zpM = 67_760;
лучше писать сразу английским термином ели мы говорим о зарплате и надо писать salary например.

2022-01-09 17:52 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        int daysMode1 = targetInKg * 1000 / mode1;
1000 необходимо вынести в переменную обозначающее что это, иначе это усложняет понимание кода

2022-01-09 17:52 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        int daysMode1 = targetInKg * 1000 / mode1;
Тем более она очень часто встречается

2022-01-09 17:52 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        short mode1 = 250;
И что обозначает mode1 и mode2? Назовите логичнее и понятнее

2022-01-09 17:52 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        int daysAverage = targetInKg * 1000 / ((mode1+mode2) / 2) + 1; /*формулировку "в среднем" трактую
Тут просто необходимо взять минимальное количество дней и максимальное, а затем просто поделить на 2

2022-01-09 17:52 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        var diffM = (zpM2 - zpM) * 12;
12 тоже стоит вынести в отдельную переменную, это удобно если мы вынесем этот код в метод, и будем считать за другой срок.

2022-01-09 17:52 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        var totalWeightInKg = totalWeight / 1000;
Тут можно легко обойтись без var, так как суть урока познакомиться с переменными и их типами.

2022-01-09 17:52 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        float zpD2 = zpD * 1.1f;
В задании ожидается, что вы явно будете использовать приведение типов. https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.16

2022-01-09 19:57 UTC, odin11 commented on src/ru/skypro/Main.java
> +        int daysAverage = targetInKg * 1000 / ((mode1+mode2) / 2) + 1; /*формулировку "в среднем" трактую
fixed

2022-01-09 19:57 UTC, odin11 commented on src/ru/skypro/Main.java
> +        float w1 = 78.2f;
fixed

2022-01-09 19:57 UTC, odin11 commented on src/ru/skypro/Main.java
> +        int zpM = 67_760;
fixed

2022-01-09 19:57 UTC, odin11 commented on src/ru/skypro/Main.java
> +        int daysMode1 = targetInKg * 1000 / mode1;
fixed

2022-01-09 19:57 UTC, odin11 commented on src/ru/skypro/Main.java
> +        short mode1 = 250;
fixed

2022-01-09 19:58 UTC, odin11 commented on src/ru/skypro/Main.java
> +        var diffM = (zpM2 - zpM) * 12;
fixed

2022-01-09 19:59 UTC, odin11 commented on src/ru/skypro/Main.java
> +        byte wBanana = 80;
fixed

2022-01-09 20:01 UTC, odin11 commented on src/ru/skypro/Main.java
> +        var totalWeightInKg = totalWeight / 1000;
fixed

2022-01-09 20:02 UTC, odin11 commented on src/ru/skypro/Main.java
> +        int totalWeight = 5 * wBanana + 200/100 * wMilkPer100Ml + 2 * wPlombir + 4 * wEgg;
fixed

2022-01-09 20:09 UTC, odin11 commented on src/ru/skypro/Main.java
> +        float zpD2 = zpD * 1.1f;
fixed

2022-01-09 23:39 UTC, rmuhamedgaliev approved these changes
Вижу исправления! Принято!

2022-01-10 16:26 UTC, merged